theme: jekyll-theme-minimal
title: Heath Kelley
logo: images/profilepicture.png

docs_list_title: Site Navigation
docs:

- title: Home
  url: /README.md

- title: Growth Mindset
  url: /growthmindset.md
